#general
N_RUNS = 1
PROBLEM_SIZE = 30
MAX_GRADE = 6
N_EPOCHS = 400

#feasibility
FEASIBLE_ONLY = 1
INFEASIBLE_ALLOWED = 2

#evolutionary algorithm
POPULATION_SIZE = 300
CROSSOVER_PROBABILITY = 1.0
MUTATION_PROBABILITY = 0.01
PENALTY_CONSTANT = 5
ELITE_SIZE = 240


#selection
SELECTION_ROULETTE = 1
SELECTION_TOURNAMENT = 2
#crossover
CROSSOVER_SINGLE_POINT = 1
CROSSOVER_UNIFORM = 2
CROSSOVER_ARITHMETIC = 3
CROSSOVER_NONE = 4
#mutation
MUTATION_GAUSS = 1
MUTATION_RANDOM = 2
#succession
SUCCESSION_GENERATIONAL = 1
SUCCESSION_ELITE = 2


