#general
N_RUNS = 1
PROBLEM_SIZE = 30
MAX_GRADE = 6

#evolutionary algorithm
POPULATION_SIZE = 100
CROSSOVER_PROBABILITY = 0.1
MUTATION_PROBABILITY = 0.01
PENALTY_CONSTANT = 1


#selection
SELECTION_ROULETTE = 1
SELECTION_TOURNAMENT = 2
#crossover
CROSSOVER_SINGLE_POINT = 1
CROSSOVER_UNIFORM = 2
CROSSOVER_ARITHMETIC = 3
CROSSOVER_NONE = 4
#mutation
MUTATION_GAUSS = 1
MUTATION_RANDOM = 2
#succession
SUCCESSION_GENERATIONAL = 1
SUCCESSION_ELITE = 2


